# Artificial Neural Network

Reference Codes: https://colab.research.google.com/drive/1eje9zILprgVmohMN7cKykI3fn4FBRPnF

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values # All rows, all columns except the last one
y = dataset.iloc[:, -1].values # All rows, last column only

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) # test_size is the size of the test set, meaning number of observations of the test set

In [ ]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [ ]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [ ]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [ ]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the third hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the fourth hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the fifth hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))
# The Dense() class refers to the connection between the input layer and this current layer.
# units is the number of hidden neurons inside this output layer.
# We do not need the activation function here.

# classification with only 2 categories => sigmoid activation function
# classification with more than 2 categories => softmax activation function
# regression (predict continuous real number) => NO activation function

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
# adam optimizer is the most common optimizer

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)
# 100 is a good number of epochs

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 125384.6641
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 381.8716
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 371.2776
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 358.2003
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 342.6894
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 326.2275
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 306.7505
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 286.3349
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 266.7690
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 243.1123
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 221.6636
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

### Predicting the results of the Test set

In [ ]:
# Calculate the predicted output
y_pred = ann.predict(X_test)
# Set the precision
np.set_printoptions(precision=2)
# Compare the predicted output with the real output of the test set
results = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
# Reshape y_pred 1D array into a matrix of 1 row and len(y_pred) columns. Same for y_test
# For the last param of the concatenate function
## 1 => vertical concatenation
## 0 => horizontal concatenation

# Look at the output, you'll see that the predicted output and real output are pretty close, which means out ANN performs really well

In [ ]:
for result in results:
  print(result)

[431.4  431.23]
[462.55 460.01]
[466.09 461.14]
[449.14 445.9 ]
[460.32 451.29]
[429.52 432.68]
[471.88 477.5 ]
[457.92 459.68]
[475.45 477.5 ]
[444.4  444.99]
[442.47 444.37]
[442.08 437.04]
[446.8  442.34]
[442.5  440.74]
[438.22 436.55]
[456.08 460.24]
[448.17 448.66]
[437.47 432.94]
[451.51 452.82]
[428.62 432.2 ]
[425.27 430.96]
[430.88 434.65]
[478.37 473.56]
[437.35 434.47]
[446.83 450.92]
[454.62 452.82]
[478.41 485.94]
[445.67 435.47]
[452.91 448.96]
[466.77 465.89]
[475.61 482.52]
[463.24 465.05]
[475.17 475.51]
[467.67 466.71]
[469.66 472.42]
[433.66 434.64]
[464.84 467.97]
[483.68 481.86]
[433.96 437.72]
[473.4  470.49]
[447.17 449.04]
[466.96 468.15]
[459.52 457.94]
[481.71 486.4 ]
[446.35 443.52]
[441.38 442.23]
[434.68 430.61]
[439.68 439.72]
[471.04 467.98]
[440.99 433.36]
[457.29 448.74]
[464.13 464.39]
[440.07 443.06]
[467.24 470.23]
[460.08 467.21]
[445.44 449.1 ]
[483.58 487.33]
[481.55 473.73]
[462.09 461.96]
[485.02 483.12]
[438.17 433.81]
[452.45 444.05]
[472.2  