# Artificial Neural Network

Reference Codes: https://colab.research.google.com/drive/1eje9zILprgVmohMN7cKykI3fn4FBRPnF

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values # All rows, all columns except the last one
y = dataset.iloc[:, -1].values # All rows, last column only

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) # test_size is the size of the test set, meaning number of observations of the test set

In [ ]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [ ]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [ ]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [ ]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))
# The Dense() class refers to the connection between the input layer and this current layer.
# units is the number of hidden neurons inside this output layer.
# We do not need the activation function here.

# classification with only 2 categories => sigmoid activation function
# classification with more than 2 categories => softmax activation function
# regression (predict continuous real number) => NO activation function

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
# adam optimizer is the most common optimizer

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)
# 100 is a good number of epochs

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 42261.8086
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 472.7929
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 447.2199
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 416.3754
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 382.1589
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 347.1996
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 308.0177
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 269.3842
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 230.2231
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 190.1653
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 152.1557
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

### Predicting the results of the Test set

In [ ]:
# Calculate the predicted output
y_pred = ann.predict(X_test)
# Set the precision
np.set_printoptions(precision=2)
# Compare the predicted output with the real output of the test set
results = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
# Reshape y_pred 1D array into a matrix of 1 row and len(y_pred) columns. Same for y_test
# For the last param of the concatenate function
## 1 => vertical concatenation
## 0 => horizontal concatenation

# Look at the output, you'll see that the predicted output and real output are pretty close, which means out ANN performs really well

In [ ]:
for result in results:
  print(result)

[430.97 431.23]
[461.93 460.01]
[465.41 461.14]
[448.58 445.9 ]
[459.77 451.29]
[429.05 432.68]
[471.29 477.5 ]
[457.31 459.68]
[474.84 477.5 ]
[443.73 444.99]
[441.93 444.37]
[441.61 437.04]
[446.23 442.34]
[441.93 440.74]
[437.78 436.55]
[455.39 460.24]
[447.67 448.66]
[436.97 432.94]
[450.95 452.82]
[428.12 432.2 ]
[424.81 430.96]
[430.35 434.65]
[477.73 473.56]
[436.89 434.47]
[446.3  450.92]
[453.92 452.82]
[477.81 485.94]
[445.2  435.47]
[452.26 448.96]
[466.12 465.89]
[475.03 482.52]
[462.56 465.05]
[474.52 475.51]
[467.06 466.71]
[469.02 472.42]
[433.18 434.64]
[464.15 467.97]
[483.03 481.86]
[433.46 437.72]
[472.69 470.49]
[446.68 449.04]
[466.28 468.15]
[458.97 457.94]
[481.11 486.4 ]
[445.78 443.52]
[440.82 442.23]
[434.13 430.61]
[439.11 439.72]
[470.4  467.98]
[440.48 433.36]
[456.63 448.74]
[463.6  464.39]
[439.59 443.06]
[466.56 470.23]
[459.4  467.21]
[444.93 449.1 ]
[482.99 487.33]
[480.99 473.73]
[461.44 461.96]
[484.41 483.12]
[437.69 433.81]
[451.9  444.05]
[471.54 