# Artificial Neural Network

Reference Codes: https://colab.research.google.com/drive/1eje9zILprgVmohMN7cKykI3fn4FBRPnF

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values # All rows, all columns except the last one
y = dataset.iloc[:, -1].values # All rows, last column only

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) # test_size is the size of the test set, meaning number of observations of the test set

In [ ]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [ ]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [ ]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [ ]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the third hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the fourth hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))
# The Dense() class refers to the connection between the input layer and this current layer.
# units is the number of hidden neurons inside this output layer.
# We do not need the activation function here.

# classification with only 2 categories => sigmoid activation function
# classification with more than 2 categories => softmax activation function
# regression (predict continuous real number) => NO activation function

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
# adam optimizer is the most common optimizer

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)
# 100 is a good number of epochs

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 140698.2188
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 305.1414
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 265.9510
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 256.2092
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 246.5813
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 234.9049
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 221.4676
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 209.6186
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 195.5687
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 179.9092
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 163.7794
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

### Predicting the results of the Test set

In [ ]:
# Calculate the predicted output
y_pred = ann.predict(X_test)
# Set the precision
np.set_printoptions(precision=2)
# Compare the predicted output with the real output of the test set
results = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
# Reshape y_pred 1D array into a matrix of 1 row and len(y_pred) columns. Same for y_test
# For the last param of the concatenate function
## 1 => vertical concatenation
## 0 => horizontal concatenation

# Look at the output, you'll see that the predicted output and real output are pretty close, which means out ANN performs really well

In [ ]:
for result in results:
  print(result)

[431.85 431.23]
[462.99 460.01]
[466.61 461.14]
[449.54 445.9 ]
[460.66 451.29]
[429.93 432.68]
[472.19 477.5 ]
[458.33 459.68]
[475.75 477.5 ]
[444.9  444.99]
[442.93 444.37]
[442.42 437.04]
[447.18 442.34]
[443.04 440.74]
[438.69 436.55]
[456.53 460.24]
[448.46 448.66]
[437.8  432.94]
[452.02 452.82]
[429.06 432.2 ]
[425.73 430.96]
[431.41 434.65]
[478.76 473.56]
[437.87 434.47]
[447.31 450.92]
[455.21 452.82]
[478.79 485.94]
[446.   435.47]
[453.28 448.96]
[467.14 465.89]
[475.94 482.52]
[463.62 465.05]
[475.5  475.51]
[468.04 466.71]
[469.97 472.42]
[434.03 434.64]
[465.32 467.97]
[483.99 481.86]
[434.41 437.72]
[473.72 470.49]
[447.56 449.04]
[467.47 468.15]
[459.92 457.94]
[482.01 486.4 ]
[446.77 443.52]
[441.89 442.23]
[435.18 430.61]
[440.13 439.72]
[471.46 467.98]
[441.37 433.36]
[457.77 448.74]
[464.45 464.39]
[440.57 443.06]
[467.63 470.23]
[460.55 467.21]
[445.85 449.1 ]
[483.82 487.33]
[481.67 473.73]
[462.51 461.96]
[485.24 483.12]
[438.64 433.81]
[452.87 444.05]
[472.49 