# Artificial Neural Network

Reference Codes: https://colab.research.google.com/drive/1eje9zILprgVmohMN7cKykI3fn4FBRPnF

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values # All rows, all columns except the last one
y = dataset.iloc[:, -1].values # All rows, last column only

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) # test_size is the size of the test set, meaning number of observations of the test set

In [ ]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [ ]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [ ]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [ ]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the third hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The Dense() class refers to the connection between the input layer and the hidden layer
# units is the number of hidden neurons inside this hidden layer
# The activation function here is the rectifier function (relu)

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))
# The Dense() class refers to the connection between the input layer and this current layer.
# units is the number of hidden neurons inside this output layer.
# We do not need the activation function here.

# classification with only 2 categories => sigmoid activation function
# classification with more than 2 categories => softmax activation function
# regression (predict continuous real number) => NO activation function

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
# adam optimizer is the most common optimizer

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)
# 100 is a good number of epochs

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 46198.8633
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 573.9357
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 551.3793
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 523.0533
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 490.9097
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 453.8928
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 413.6311
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 372.0682
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 327.1526
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 281.6157
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 237.3127
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - lo

### Predicting the results of the Test set

In [ ]:
# Calculate the predicted output
y_pred = ann.predict(X_test)
# Set the precision
np.set_printoptions(precision=2)
# Compare the predicted output with the real output of the test set
results = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
# Reshape y_pred 1D array into a matrix of 1 row and len(y_pred) columns. Same for y_test
# For the last param of the concatenate function
## 1 => vertical concatenation
## 0 => horizontal concatenation

# Look at the output, you'll see that the predicted output and real output are pretty close, which means out ANN performs really well

In [ ]:
for result in results:
  print(result)

[433.59 431.23]
[461.47 460.01]
[466.53 461.14]
[447.89 445.9 ]
[457.89 451.29]
[432.13 432.68]
[471.78 477.5 ]
[456.21 459.68]
[475.7 477.5]
[443.33 444.99]
[442.43 444.37]
[442.48 437.04]
[446.36 442.34]
[442.43 440.74]
[438.94 436.55]
[454.88 460.24]
[447.95 448.66]
[438.71 432.94]
[449.47 452.82]
[431.55 432.2 ]
[428.63 430.96]
[432.73 434.65]
[479.41 473.56]
[437.71 434.47]
[445.59 450.92]
[454.1  452.82]
[480.03 485.94]
[445.48 435.47]
[450.99 448.96]
[466.6  465.89]
[476.14 482.52]
[462.75 465.05]
[475.85 475.51]
[467.44 466.71]
[469.51 472.42]
[435.55 434.64]
[465.56 467.97]
[485.19 481.86]
[435.61 437.72]
[474.24 470.49]
[446.47 449.04]
[467.87 468.15]
[457.32 457.94]
[482.68 486.4 ]
[446.01 443.52]
[441.61 442.23]
[436.29 430.61]
[440.38 439.72]
[471.59 467.98]
[441.51 433.36]
[456.55 448.74]
[462.28 464.39]
[440.25 443.06]
[467.52 470.23]
[460.24 467.21]
[445.26 449.1 ]
[484.67 487.33]
[481.38 473.73]
[461.32 461.96]
[486.47 483.12]
[438.77 433.81]
[451.   444.05]
[471.88 45